import { execFile } from "node:child_process";
import { existsSync, readFileSync, statSync } from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve } from "node:path";
import type { Container } from "@oh-my-pi/pi-tui";
import type { ExtensionApi, ToolResult } from "../core/api.ts";
import { toolResultCard } from "../research/research-format.ts";

const UNDERSCORE_RE = /_/g;
const repoRootCache = new Map<string, string>();
export interface RoutineParameter {
  name: string;
  default?: string;
  description?: string;
}

export interface RoutineEntry {
  id: string;
  name: string;
  file: string;
  description?: string;
  parameters?: RoutineParameter[];
  tags?: string[];
}

export interface RoutineManifest {
  routines: RoutineEntry[];
}

export interface RoutineExecutionDetails {
  routineId: string;
  name: string;
  file?: string;
  scriptPath?: string;
  exitCode: number;
  stdout: string;
  stderr: string;
  args?: Record<string, string>;
  success: boolean;
  error?: string;
}
export interface ScaffoldExtensionOptions {
  slug: string;
  description: string;
  commandName?: string;
  options?: Array<{ value: string; label: string; description?: string }>;
  implementationBody?: string;
}

export interface GraduateSkillOptions {
  skillPath: string;
  skillContent: string;
  slug?: string;
}

/**
 * Validate that a generated TypeScript extension has valid syntax and exports a default function.
 */
export function validateExtensionSyntax(content: string): { valid: boolean; error?: string } {
  if (!content || !content.trim()) {
    return { valid: false, error: "Extension content cannot be empty" };
  }

  // Check for export default function
  if (!/export\s+default\s+(?:function|\()/m.test(content) && !/export\s+default\s+[a-zA-Z0-9_$]+/m.test(content)) {
    return { valid: false, error: "Extension must export a default function receiving ExtensionApi" };
  }

  // Check for basic delimiter balance (braces, parens, brackets)
  const stack: string[] = [];
  const pairs: Record<string, string> = { "}": "{", ")": "(", "]": "[" };
  let inString: string | null = null;
  let inComment = false;

  for (let i = 0; i < content.length; i++) {
    const ch = content[i];
    const next = content[i + 1];

    if (inComment) {
      if (ch === "\n" && inComment) inComment = false;
      continue;
    }
    if (ch === "/" && next === "/") {
      inComment = true;
      i++;
      continue;
    }

    if (inString) {
      if (ch === "\\" ) { i++; continue; }
      if (ch === inString) inString = null;
      continue;
    }

    if (ch === '"' || ch === "'" || ch === "`") {
      inString = ch;
      continue;
    }

    if (ch === "{" || ch === "(" || ch === "[") {
      stack.push(ch);
    } else if (ch === "}" || ch === ")" || ch === "]") {
      const last = stack.pop();
      if (last !== pairs[ch]) {
        return { valid: false, error: `Mismatched delimiter: '${ch}' does not match '${last ?? "none"}'` };
      }
    }
  }

  if (stack.length > 0) {
    return { valid: false, error: `Unclosed delimiter: '${stack[stack.length - 1]}'` };
  }

  return { valid: true };
}

/**
 * Scaffold a canonical local modular extension template (.omp/extensions/<slug>.ts).
 */
export function scaffoldLocalExtension(options: ScaffoldExtensionOptions): { path: string; content: string } {
  const slug = options.slug.toLowerCase().replace(/[^a-z0-9_-]+/g, "-");
  const cmd = options.commandName || slug;
  const description = options.description.replace(/"/g, '\\"');
  const body = options.implementationBody || `ctx.ui?.notify?.("Executed ${cmd}", "info");`;

  const compOptions = options.options && options.options.length > 0
    ? options.options
    : [{ value: "default", label: "default", description: "Standard execution" }];

  const compJson = JSON.stringify(compOptions, null, 8).trim();

  const content = `// .omp/extensions/${slug}.ts
// Local harness extension generated by /routinize

export interface ExtensionApi {
  registerCommand(name: string, def: {
    description: string;
    getArgumentCompletions?: (prefix: string) => Array<{ value: string; label: string; description?: string }> | null;
    handler: (args: string, ctx: { ui?: { notify?: (msg: string, level?: string) => void } }) => Promise<void> | void;
  }): void;
}

export default function (pi: ExtensionApi): void {
  pi.registerCommand("${cmd}", {
    description: "${description}",
    getArgumentCompletions: (prefix: string) => {
      const options = ${compJson};
      const lower = prefix.toLowerCase().trim();
      return lower ? options.filter((o) => o.value.startsWith(lower)) : options;
    },
    handler: async (args: string, ctx) => {
      ${body}
    },
  });
}
`;

  return {
    path: `.omp/extensions/${slug}.ts`,
    content,
  };
}

/**
 * Heuristic analyzer checking if a markdown skill is a purely procedural candidate for graduation.
 */
export function isSkillProceduralCandidate(skillMarkdown: string): {
  isCandidate: boolean;
  estimatedTokenSavings: number;
  reason?: string;
} {
  const tokenLength = Math.round(skillMarkdown.length / 4);

  // Creative skills with interview loops or active methodologies are NEVER candidates
  const CREATIVE_PATTERNS = [
    /interview/i,
    /grill/i,
    /stress-test/i,
    /red-green-refactor/i,
    /domain-modeling/i,
    /prototype/i,
    /explore/i,
    /architect/i,
  ];

  for (const pattern of CREATIVE_PATTERNS) {
    if (pattern.test(skillMarkdown)) {
      return {
        isCandidate: false,
        estimatedTokenSavings: 0,
        reason: "Skill contains creative reasoning, interview loops, or architectural heuristics",
      };
    }
  }

  // Check for procedural indicators (dense bash commands, CLI flags, build/lint incantations)
  const PROCEDURAL_PATTERNS = [
    /```bash\b[\s\S]*?```/,
    /npm run /i,
    /cargo /i,
    /pytest /i,
    /python /i,
    /docker /i,
    /slurm|sbatch/i,
    /curl /i,
  ];

  const proceduralMatches = PROCEDURAL_PATTERNS.filter((p) => p.test(skillMarkdown));
  if (proceduralMatches.length >= 1) {
    return {
      isCandidate: true,
      estimatedTokenSavings: tokenLength,
      reason: "Skill consists of purely deterministic CLI commands and procedural flag invocations",
    };
  }

  return {
    isCandidate: false,
    estimatedTokenSavings: 0,
    reason: "Skill does not match procedural CLI criteria",
  };
}

/**
 * Graduate a procedural markdown skill to a local TypeScript extension.
 */
export function graduateSkillToExtension(options: GraduateSkillOptions): {
  extensionPath: string;
  extensionContent: string;
  skillPathToDelete: string;
  tokenSavings: number;
} {
  const { skillPath, skillContent, slug: explicitSlug } = options;
  const inferredSlug = explicitSlug || basename(dirname(skillPath)).toLowerCase().replace(/[^a-z0-9_-]+/g, "-");

  // Extract description from frontmatter or first paragraph
  const descMatch = skillContent.match(/description:\s*(.+)$/m);
  const description = descMatch ? descMatch[1].trim().replace(/^['"]|['"]$/g, "") : `Graduated command for ${inferredSlug}`;

  // Extract CLI commands from code blocks
  const cmdMatches = skillContent.match(/```(?:bash|sh)\s*\n([\s\S]*?)\n```/);
  const cliScript = cmdMatches ? cmdMatches[1].trim() : `echo "Running ${inferredSlug}..."`;

  const scaffold = scaffoldLocalExtension({
    slug: inferredSlug,
    description,
    implementationBody: `ctx.ui?.notify?.("Executing ${inferredSlug}...", "info");\n      // Graduated from ${skillPath}\n      // Script: ${cliScript.split("\n")[0]}`,
  });

  return {
    extensionPath: scaffold.path,
    extensionContent: scaffold.content,
    skillPathToDelete: skillPath,
    tokenSavings: Math.round(skillContent.length / 4),
  };
}

export function findRoutinesRepoRoot(startDir: string = process.cwd()): string {
  const cached = repoRootCache.get(startDir);
  if (cached !== undefined) return cached;
  let dir = startDir;
  for (;;) {
    const manifestPath = join(dir, "scripts", "routines", "manifest.json");
    if (existsSync(manifestPath)) {
      repoRootCache.set(startDir, dir);
      return dir;
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // Fallback: search for root marker (.git, .omp, .scratch, package.json)
  dir = startDir;
  for (;;) {
    if (
      existsSync(join(dir, ".git")) ||
      existsSync(join(dir, ".omp")) ||
      existsSync(join(dir, ".scratch")) ||
      existsSync(join(dir, "package.json"))
    ) {
      repoRootCache.set(startDir, dir);
      return dir;
    }
    const parent = dirname(dir);
    if (parent === dir) {
      repoRootCache.set(startDir, startDir);
      return startDir;
    }
    dir = parent;
  }
}

export function renderRoutineResult(result: ToolResult): Container {
  const details = result.details as RoutineExecutionDetails | undefined;
  const name = details?.name ?? details?.routineId ?? "Routine";
  const code = details?.exitCode ?? (details?.success === false ? 1 : 0);
  const label = `ROUTINE — ${name} (exit ${code})`;
  const summary = details?.stdout || details?.stderr || details?.error || (result.content[0]?.text ?? "");
  const lines = summary
    .split("\n")
    .map((l) => l.trimEnd())
    .filter(Boolean)
    .slice(0, 8);
  if (lines.length === 0) lines.push(code === 0 ? "completed with no output" : "failed with no output");

  return toolResultCard(lines, label);
}

export function installRoutinesTool(pi: ExtensionApi): void {
  const { zod } = pi;

  pi.registerTool({
    name: "run_routine",
    label: "Run Routine",
    description:
      "Execute a parameterized routine script from scripts/routines/ using metadata from manifest.json",
    parameters: zod.object({
      routineId: zod.string(),
      args: zod.record(zod.string(), zod.string()).optional(),
    }),
    execute: async (_toolCallId, rawParams, signal, _onUpdate, ctx) => {
      const params = rawParams as { routineId: string; args?: Record<string, string> };
      const repoRoot = findRoutinesRepoRoot(ctx.cwd);
      const routinesDir = join(repoRoot, "scripts", "routines");
      const manifestPath = join(routinesDir, "manifest.json");

      const resolvedRoutine = resolve(routinesDir, params.routineId);
      const relRoutine = relative(routinesDir, resolvedRoutine);
      if (relRoutine.startsWith("..") || isAbsolute(relRoutine)) {
        const msg = `Error: Path traversal attempt detected for routineId "${params.routineId}"`;
        return {
          content: [{ type: "text", text: msg }],
          details: {
            routineId: params.routineId,
            name: params.routineId,
            exitCode: 1,
            stdout: "",
            stderr: msg,
            success: false,
            error: msg,
          },
        };
      }

      let routineEntry: RoutineEntry | undefined;
      let scriptFile: string | undefined;
      let routineName: string | undefined;

      if (existsSync(manifestPath)) {
        try {
          const raw = readFileSync(manifestPath, "utf8");
          const manifest = JSON.parse(raw) as RoutineManifest;
          if (manifest && Array.isArray(manifest.routines)) {
            routineEntry = manifest.routines.find(
              (r) =>
                r &&
                typeof r === "object" &&
                (r.id === params.routineId ||
                  r.file === params.routineId ||
                  (typeof r.file === "string" && basename(r.file) === params.routineId) ||
                  (typeof r.name === "string" && r.name.toLowerCase() === params.routineId.toLowerCase())),
            );
          }
        } catch {
          // Ignore manifest parse errors
        }
      }

      if (routineEntry) {
        scriptFile = routineEntry.file;
        routineName = routineEntry.name;
      } else {
        const candidateSh = params.routineId.endsWith(".sh")
          ? params.routineId
          : `${params.routineId}.sh`;
        if (existsSync(join(routinesDir, params.routineId))) {
          scriptFile = params.routineId;
          routineName = params.routineId;
        } else if (existsSync(join(routinesDir, candidateSh))) {
          scriptFile = candidateSh;
          routineName = params.routineId;
        }
      }

      if (!scriptFile) {
        const msg = `Error: Routine "${params.routineId}" not found in scripts/routines/manifest.json or scripts/routines/`;
        return {
          content: [{ type: "text", text: msg }],
          details: {
            routineId: params.routineId,
            name: params.routineId,
            exitCode: 1,
            stdout: "",
            stderr: msg,
            success: false,
            error: `Routine "${params.routineId}" not found`,
          },
        };
      }

      const scriptPath = resolve(routinesDir, scriptFile);
      const relScript = relative(routinesDir, scriptPath);
      if (relScript.startsWith("..") || isAbsolute(relScript)) {
        const msg = `Error: Path traversal attempt detected for script "${scriptFile}"`;
        return {
          content: [{ type: "text", text: msg }],
          details: {
            routineId: params.routineId,
            name: routineName ?? params.routineId,
            file: scriptFile,
            scriptPath,
            exitCode: 1,
            stdout: "",
            stderr: msg,
            success: false,
            error: msg,
          },
        };
      }
      if (!existsSync(scriptPath)) {
        const msg = `Error: Routine script file "${scriptPath}" does not exist.`;
        return {
          content: [{ type: "text", text: msg }],
          details: {
            routineId: params.routineId,
            name: routineName ?? params.routineId,
            file: scriptFile,
            scriptPath,
            exitCode: 1,
            stdout: "",
            stderr: msg,
            success: false,
            error: `Script file not found: ${scriptPath}`,
          },
        };
      }

      const effectiveArgs: Record<string, string> = {};
      if (routineEntry?.parameters && Array.isArray(routineEntry.parameters)) {
        for (const p of routineEntry.parameters) {
          if (p && p.default !== undefined && typeof p.name === "string" && p.name.length > 0) {
            effectiveArgs[p.name] = p.default;
          }
        }
      }
      for (const [k, v] of Object.entries(params.args ?? {})) {
        if (typeof v === "string") {
          effectiveArgs[k] = v;
        }
      }

      const env: Record<string, string | undefined> = { ...process.env };
      const cliFlags: string[] = [];

      for (const [k, v] of Object.entries(effectiveArgs)) {
        env[k] = v;
        env[k.toUpperCase()] = v;
        if (k.startsWith("-")) {
          cliFlags.push(k, v);
        } else if (k.length === 1) {
          cliFlags.push(`-${k}`, v);
        } else {
          cliFlags.push(`--${k.toLowerCase().replace(UNDERSCORE_RE, "-")}`, v);
        }
      }

      const isSh = scriptPath.endsWith(".sh");
      const isTs = scriptPath.endsWith(".ts") || scriptPath.endsWith(".js");
      const cmd = isSh ? "bash" : isTs ? "bun" : scriptPath;
      const cmdArgs = isSh || isTs ? [scriptPath, ...cliFlags] : cliFlags;

      return new Promise<ToolResult>((resolve) => {
        execFile(
          cmd,
          cmdArgs,
          { env: env as Record<string, string>, cwd: repoRoot, signal, timeout: 60000 },
          (error, stdoutBuf, stderrBuf) => {
            const stdout = String(stdoutBuf ?? "");
            const stderr = String(stderrBuf ?? "");
            let exitCode = 0;
            if (error) {
              if (typeof error === "object" && error !== null && "code" in error && typeof error.code === "number") {
                exitCode = error.code;
              } else {
                exitCode = 1;
              }
            }

            const outputLines: string[] = [];
            if (stdout) outputLines.push(stdout);
            if (stderr) outputLines.push(`Stderr:\n${stderr}`);
            if (error && !stdout && !stderr) outputLines.push(`Execution error: ${error.message}`);
            const text = outputLines.join("\n\n") || `Routine completed with exit code ${exitCode}`;

            resolve({
              content: [{ type: "text", text }],
              details: {
                routineId: params.routineId,
                name: routineName ?? params.routineId,
                file: scriptFile,
                scriptPath,
                exitCode,
                stdout,
                stderr,
                args: effectiveArgs,
                success: exitCode === 0,
                ...(error ? { error: error.message } : {}),
              },
            });
          },
        );
      });
    },
    renderResult: renderRoutineResult,
  });
}
